# Generated by Django 5.2.6 on 2025-09-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuthGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
            ],
            options={
                'db_table': 'auth_group',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthGroupPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_group_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('codename', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'auth_permission',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128)),
                ('last_login', models.DateTimeField(blank=True, null=True)),
                ('is_superuser', models.IntegerField()),
                ('username', models.CharField(max_length=150, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=254)),
                ('is_staff', models.IntegerField()),
                ('is_active', models.IntegerField()),
                ('date_joined', models.DateTimeField()),
            ],
            options={
                'db_table': 'auth_user',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserGroups',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_groups',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AuthUserUserPermissions',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'auth_user_user_permissions',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BasicTusi',
            fields=[
                ('tusi_id', models.IntegerField(db_comment='土司编号', primary_key=True, serialize=False)),
                ('tusi_name', models.CharField(db_comment='土司中文名字', max_length=255, unique=True)),
                ('tusi_type', models.CharField(db_collation='utf8mb4_0900_ai_ci', db_comment='土司类型', max_length=4)),
                ('start_date_1', models.CharField(blank=True, db_comment='土司成立时间（朝代）', max_length=255, null=True)),
                ('start_date_2', models.CharField(blank=True, db_comment='土司成立时间(年号）', max_length=255, null=True)),
                ('start_date_3', models.CharField(blank=True, db_comment='土司成立时间(具体年份-中文）', max_length=255, null=True)),
                ('start_date_4', models.IntegerField(blank=True, db_comment='土司成立时间(数字时间）', null=True)),
                ('end_date_1', models.CharField(blank=True, db_comment='土司废除时间（朝代）', max_length=255, null=True)),
                ('end_date_2', models.CharField(blank=True, db_comment='土司废除时间（年号）', max_length=255, null=True)),
                ('end_date_3', models.CharField(blank=True, db_comment='土司废除时间（具体年份-中文）', max_length=255, null=True)),
                ('end_date_4', models.IntegerField(blank=True, db_comment='土司废除时间（数字时间）', null=True)),
                ('end_reason', models.CharField(blank=True, db_comment='土司废除的原因', max_length=255, null=True)),
                ('belong_state', models.CharField(db_comment='土司上属行政区划', max_length=255)),
                ('author', models.CharField(db_comment='作者', max_length=255)),
            ],
            options={
                'db_table': 'basic_tusi',
                'db_table_comment': '土司基础信息',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BasicXiajing',
            fields=[
                ('xiajing_id', models.IntegerField(db_comment='土司辖境释文编号', primary_key=True, serialize=False)),
                ('xiajing_text', models.TextField(db_comment='辖境释文编号')),
            ],
            options={
                'db_table': 'basic_xiajing',
                'db_table_comment': '土司辖境范围',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BasicZhiguan',
            fields=[
                ('zhiguan_id', models.IntegerField(db_comment='土司职官编号', primary_key=True, serialize=False)),
                ('zhiguan_name', models.CharField(db_comment='就任土司人员名字', max_length=255, unique=True)),
                ('zhiguan_type', models.CharField(db_comment='土司职官类型', max_length=4)),
                ('gender', models.CharField(db_comment='土司人员性别', max_length=1)),
                ('birth_date_1', models.CharField(blank=True, db_comment='出生时间（朝代）', max_length=255, null=True)),
                ('birth_date_2', models.CharField(blank=True, db_comment='出生时间(年号）', max_length=255, null=True)),
                ('birth_date_3', models.CharField(blank=True, db_comment='出生时间(具体年份-中文）', max_length=255, null=True)),
                ('birth_date_4', models.IntegerField(blank=True, db_comment='出生时间(数字时间）', null=True)),
                ('start_date_1', models.CharField(blank=True, db_comment='就职时间（朝代）', max_length=255, null=True)),
                ('start_date_2', models.CharField(blank=True, db_comment='就职时间(年号）', max_length=255, null=True)),
                ('start_date_3', models.CharField(blank=True, db_comment='就职时间(具体年份-中文）', max_length=255, null=True)),
                ('start_date_4', models.IntegerField(blank=True, db_comment='就职时间(数字时间）', null=True)),
                ('end_date_1', models.CharField(blank=True, db_comment='卸任时间（朝代）', max_length=255, null=True)),
                ('end_date_2', models.CharField(blank=True, db_comment='卸任时间(年号）', max_length=255, null=True)),
                ('end_date_3', models.CharField(blank=True, db_comment='卸任时间(具体年份）', max_length=255, null=True)),
                ('end_date_4', models.IntegerField(blank=True, db_comment='卸任时间(数字时间）', null=True)),
                ('death_date_1', models.CharField(blank=True, db_comment='死亡时间（朝代）', max_length=255, null=True)),
                ('death_date_2', models.CharField(blank=True, db_comment='死亡时间(年号）', max_length=255, null=True)),
                ('death_date_3', models.CharField(blank=True, db_comment='死亡时间(具体年份-中文）', max_length=255, null=True)),
                ('death_date_4', models.IntegerField(blank=True, db_comment='死亡时间(数字时间）', null=True)),
                ('author', models.CharField(db_comment='作者', max_length=255)),
            ],
            options={
                'db_table': 'basic_zhiguan',
                'db_table_comment': '土司职官信息',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BasicZhudi',
            fields=[
                ('zhudi_id', models.IntegerField(db_comment='土司驻地编号', primary_key=True, serialize=False)),
                ('zhudi_name', models.CharField(db_comment='土司地点名称', max_length=255, unique=True)),
                ('start_date_1', models.CharField(blank=True, db_comment='驻地设立时间（朝代）', max_length=255, null=True)),
                ('start_date_2', models.CharField(blank=True, db_comment='驻地设立时间（年号）', max_length=255, null=True)),
                ('start_date_3', models.CharField(blank=True, db_comment='驻地设立时间（具体年份-中文）', max_length=255, null=True)),
                ('start_date_4', models.IntegerField(blank=True, db_comment='驻地设立时间（数字时间）', null=True)),
                ('end_date_1', models.CharField(blank=True, db_comment='驻地撤销时间（朝代）', max_length=255, null=True)),
                ('end_date_2', models.CharField(blank=True, db_comment='驻地撤销时间（年号）', max_length=255, null=True)),
                ('end_date_3', models.CharField(blank=True, db_comment='驻地撤销时间（具体年份-中文）', max_length=255, null=True)),
                ('end_date_4', models.IntegerField(blank=True, db_comment='驻地撤销时间（数字时间）', null=True)),
                ('location', models.CharField(db_comment='驻地所在地区（精确到府）', max_length=255)),
                ('author', models.CharField(db_comment='作者', max_length=255)),
            ],
            options={
                'db_table': 'basic_zhudi',
                'db_table_comment': '土司驻地的相关信息',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoAdminLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_time', models.DateTimeField()),
                ('object_id', models.TextField(blank=True, null=True)),
                ('object_repr', models.CharField(max_length=200)),
                ('action_flag', models.PositiveSmallIntegerField()),
                ('change_message', models.TextField()),
            ],
            options={
                'db_table': 'django_admin_log',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoContentType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('app_label', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'django_content_type',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoMigrations',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('app', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('applied', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_migrations',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='DjangoSession',
            fields=[
                ('session_key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('session_data', models.TextField()),
                ('expire_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'django_session',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelationshipTusi',
            fields=[
                ('tusi_relationship_id', models.IntegerField(db_comment='土司关系编号', primary_key=True, serialize=False)),
                ('relationship', models.CharField(db_comment='土司关系', max_length=2)),
                ('author', models.CharField(db_comment='作者', max_length=255)),
            ],
            options={
                'db_table': 'relationship_tusi',
                'db_table_comment': '土司相互关系表',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelationshipXiajing',
            fields=[
                ('xiajing_relationship_id', models.IntegerField(db_comment='辖境关系编号', primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(db_comment='辖境关系类型', max_length=2)),
                ('author', models.CharField(db_comment='作者', max_length=255)),
            ],
            options={
                'db_table': 'relationship_xiajing',
                'db_table_comment': '土司辖境关系表',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelationshipZhiguan',
            fields=[
                ('zhiguan_relationship_id', models.IntegerField(db_comment='职官关系编号', primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(db_comment='关系类型', max_length=3)),
                ('author', models.CharField(db_comment='作者', max_length=255)),
            ],
            options={
                'db_table': 'relationship_zhiguan',
                'db_table_comment': '土司职官关系表',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='RelationshipZhudi',
            fields=[
                ('zhudi_relationship_id', models.IntegerField(db_comment='土司驻地关系编号', primary_key=True, serialize=False)),
                ('relationship_type', models.CharField(db_comment='关系类型', max_length=2)),
                ('author', models.CharField(db_comment='作者', max_length=255)),
            ],
            options={
                'db_table': 'relationship_zhudi',
                'db_table_comment': '土司驻地关系',
                'managed': False,
            },
        ),
    ]
