# Generated by Django 5.2.6 on 2025-09-25 01:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_input', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='basictusi',
            options={},
        ),
        migrations.AlterModelOptions(
            name='basicxiajing',
            options={},
        ),
        migrations.AlterModelOptions(
            name='basiczhiguan',
            options={},
        ),
        migrations.AlterModelOptions(
            name='basiczhudi',
            options={},
        ),
        migrations.AlterModelOptions(
            name='relationshiptusi',
            options={},
        ),
        migrations.AlterModelOptions(
            name='relationshipxiajing',
            options={},
        ),
        migrations.AlterModelOptions(
            name='relationshipzhiguan',
            options={},
        ),
        migrations.AlterModelOptions(
            name='relationshipzhudi',
            options={},
        ),
    ]
