# Generated by Django 5.2.6 on 2025-09-24 02:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_input', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='basicxiajing',
            name='author',
            field=models.ForeignKey(db_comment='作者', default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basictusi',
            name='author',
            field=models.ForeignKey(db_comment='作者', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='basiczhiguan',
            name='author',
            field=models.ForeignKey(db_comment='作者', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='basiczhudi',
            name='author',
            field=models.ForeignKey(db_comment='作者', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relationshiptusi',
            name='author',
            field=models.ForeignKey(db_comment='作者', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relationshipxiajing',
            name='author',
            field=models.ForeignKey(db_comment='作者', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relationshipzhiguan',
            name='author',
            field=models.ForeignKey(db_comment='作者', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='relationshipzhudi',
            name='author',
            field=models.ForeignKey(db_comment='作者', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
