# Generated by Django 5.2.6 on 2025-09-25 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_input', '0002_alter_basictusi_options_alter_basicxiajing_options_and_more'),
        ('data_input', '0002_basicxiajing_author_alter_basictusi_author_and_more'),
    ]

    operations = [
    ]
